### ISSUE TITLE
Wine and Dine Group Project

### ISSUE THREAD

**Issue by Ade179** [Ade179/wine-and-dine#10]
- [ ] We are two students working on this project ( @shasherazi , @Ade179 )
- [ ]  https://github.com/users/Ade179/projects/2/views/1

**Comment by ishimwezachee** [comment]
- [ ]  Great job to create a plan of the tasks that will be done on your project. but seemed like you've forgotten to add one feature, - a form that will allow user to add a new food. 
- Deletion of a recipe

**Comment by codepantha** [comment]
# STATUS: APPROVED 🟢 ✔️ 

## Hi team 👋, 

Great job implementing the required changes 👏 
In my opinion, this milestone is complete!  There is nothing else to say other than... it's time to start building :shipit: 

<img src="https://media3.giphy.com/media/QXhfUsCL8f5LYYDGis/giphy.gif"/>

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
